Feature/asb 2261 content audit accessibility cookies and contact us
Planning-Inspectorate/applications-service pull request #1036
Opened 2024-02-20 16:11 UTC by cprieststephens

## Describe your changes

2261: https://pins-ds.atlassian.net/jira/software/c/projects/ASB/boards/166?selectedIssue=ASB-2261
Content update for accessibility, cookies and contact pages.
Unit tests and e2e tests have been updated accordingly.

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [x] I have provided details on how I have tested my code
- [x] I have referenced the ticket number above
- [x] I have provided a description of the ticket
- [x] I have included unit tests to cover any testable code changes

2024-02-20 16:32 UTC, christopher-semmens approved these changes

2024-02-20 17:06 UTC, emil-placheta requested changes
Just few notes

2024-02-20 17:06 UTC, emil-placheta commented on packages/forms-web-app/src/config.js
> +		openingHours: '9:00 to 17:00'
if possible, try to be a bit more descriptive with variable names ( within reason ofc ;) ), so other devs have some context on what information is held by it. `openingHours` is a bit vague, `csOpeningHours` is only a bit longer but it we can immediately infer it relates to custommer service opening times.

2024-02-21 13:28 UTC, merged

2024-03-04 14:26 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.8.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/applications-service/releases/tag/%40pins/back-office-subscribers%401.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-04 14:29 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 2.18.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/applications-service/releases/tag/%40pins/applications-service-api%402.18.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-04 14:32 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 2.23.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/applications-service/releases/tag/%40pins/forms-web-app%402.23.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: