feat: add translations for section 51 static content
Planning-Inspectorate/applications-service pull request #1187
Opened 2024-06-10 12:51 UTC by cprieststephens

## Describe your changes

[APPLICS 88](https://pins-ds.atlassian.net/jira/software/c/projects/APPLICS/boards/242?selectedIssue=APPLICS-88): 
- Add Welsh translations for section 51 static content
- Update conditional logic with language parameters so correct content continues to be displayed once a language is selected

## Type of change 🧩

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Other (please explain in the description section above)

## Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have double checked this work does not include any hardcoded secrets or passwords
- [ ] I have made corresponding changes to the documentation
- [ ] I have provided details on how I have tested my code
- [x] I have referenced the ticket number above
- [x] I have provided a description of the ticket
- [x] I have included unit tests to cover any testable code changes

2024-06-10 15:34 UTC, emil-placheta submitted a review, later dismissed
lgtm

2024-06-10 16:20 UTC, emil-placheta requested changes
We should try to simplify those if statements and move that logic out of the template. It will be easier to handle in the controller/view-model and make template easier to read/understand.

2024-06-10 16:20 UTC, emil-placheta commented on packages/forms-web-app/src/pages/projects/section-51/index/view.njk
> +				{% if advice.length > 0 or (advice.length == 0 and (queryUrl != '?lang=en' and queryUrl != '?lang=cy' and queryUrl != '')) %}
This is not very readable. Maybe it's worth having something like `adviceExists` and `showNoAdviceMwssage` etc returned from the controller/view-model to deal with the conditional rendering of those elements?

2024-06-10 16:20 UTC, emil-placheta commented on packages/forms-web-app/src/pages/projects/section-51/index/view.njk
> +				{% if advice.length > 0 or (queryUrl != '?lang=en' and queryUrl != '?lang=cy' and queryUrl != '') %}
similarly to above

2024-06-10 16:20 UTC, emil-placheta commented on packages/forms-web-app/src/pages/projects/section-51/index/view.njk
> +				{% if advice.length == 0 and (queryUrl != '?lang=en' and queryUrl != '?lang=cy' and queryUrl != '') %}
and here

2024-06-12 09:35 UTC, cprieststephens commented on packages/forms-web-app/src/pages/projects/section-51/index/_utils/advice-helpers.js
> +// Used in conjunction with doesAdviceExist, this function clarifies whether no advice has been returned because there is none available for the case or because no advice matches the entered search t
Much better!

2024-06-13 12:12 UTC, emil-placheta requested changes

2024-06-13 12:12 UTC, emil-placheta commented on packages/forms-web-app/src/pages/projects/section-51/index/view.njk
> +{% set noAdviceExists = adviceExists == false %}
Sorry, missed that last time, you don't need to set `noAdviceExists`.
If you want to check for advice _not_ existing in a conditional statement, you can negate it in nunjucks like you would in javascript, but using different syntax:

`{% if(not adviceExists) %}
....
{% endif %}`

2024-06-13 12:12 UTC, emil-placheta commented on packages/forms-web-app/src/pages/projects/section-51/index/view.njk
> +				{% if adviceExists or (noAdviceExists and adviceSearchResult) %}
`noAdviceExists` could be `not noAdviceExists`

2024-06-19 09:33 UTC, emil-placheta approved these changes

2024-06-19 09:54 UTC, merged

2024-06-20 13:56 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 2.25.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/applications-service/releases/tag/%40pins/applications-service-api%402.25.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-20 13:58 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 2.31.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/applications-service/releases/tag/%40pins/forms-web-app%402.31.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-07-02 08:45 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.13.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/applications-service/releases/tag/%40pins/back-office-subscribers%401.13.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-07-22 13:21 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/applications-service/releases/tag/%40pins/ni-redirects%401.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: