ASB-274/275 implement search box
Planning-Inspectorate/applications-service pull request #245
Opened 2022-05-03 07:32 UTC by pk2453

2022-05-03 14:48 UTC, cpcundill requested changes

2022-05-03 16:25 UTC, cpcundill requested changes

2022-05-03 16:25 UTC, cpcundill commented on packages/forms-web-app/src/controllers/projects/documents.js
> +  const dt = moment('2019-04-22', 'YYYY-MM-DD').format('YYYY-MM-DD');
Assuming this and the line below need to be removed and was just used for some debugging?

2022-05-03 16:27 UTC, cpcundill requested changes

2022-05-03 16:27 UTC, cpcundill commented on packages/forms-web-app/src/views/layouts/project-3-columns.njk
> +            {% block filterSection %}{% endblock %}
This should still be `columnThree`

2022-05-03 16:27 UTC, cpcundill commented on packages/forms-web-app/src/views/layouts/project-3-columns.njk
> +            {% block contentHeader %}{% endblock %}
This should be `columnTwo`

2022-05-03 16:27 UTC, cpcundill commented on packages/forms-web-app/src/views/layouts/project-3-columns.njk
> +          {% block resultSec %}{% endblock %}
This should become `contentHeader`

2022-05-04 08:57 UTC, pk2453 commented on packages/forms-web-app/src/views/layouts/project-3-columns.njk
> +            {% block contentHeader %}{% endblock %}
All are changed

2022-05-04 10:17 UTC, cpcundill approved these changes

2022-05-04 10:17 UTC, merged

2022-07-06 14:12 UTC, andylangridge commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/applications-service/releases/tag/applications-service-api%401.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-07-06 14:18 UTC, andylangridge commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/applications-service/releases/tag/forms-web-app%401.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: