feat(project information): add pre exam reps logic
Planning-Inspectorate/applications-service pull request #776
Opened 2023-08-11 12:18 UTC by jonathangoulding

2023-08-11 13:51 UTC, jonathangoulding commented on packages/forms-web-app/src/pages/projects/project-information/utils/pre-examination-sub-stages.js
> +		if (dayToday.isAfter(dayWebsiteDate)) subStages.PUBLISHED_REPS = true;
"PRE_REPS":false,"OPEN_REPS":true,"CLOSED_REPS":false,"PUBLISHED_REPS":true,"RULE_6_PUBLISHED_REPS":false

Possible with dates -  Open (2017-02-14) closed (2024-08-01) websote (2021-08-17) false

Rep open and published both true

2023-08-11 14:22 UTC, jonathangoulding commented on packages/forms-web-app/src/pages/projects/project-information/utils/pre-examination-sub-stages.js
> +		if (dayToday.isAfter(dayWebsiteDate)) subStages.PUBLISHED_REPS = true;
test is fine. But when rendered it shows true.

2023-08-16 12:34 UTC, Yakitrak requested changes
Looks good, just a few minor comments

2023-08-16 12:50 UTC, Yakitrak commented on packages/forms-web-app/src/pages/projects/project-information/utils/pre-examination-sub-stages.js
> +	if (dayToday.isAfter(dayOpenDate) && (dayToday.isBefore(dayClosedDate) || closedDate === null))
Do we have logic somewhere to catch this empty page?

2023-08-16 12:51 UTC, jonathangoulding commented on packages/forms-web-app/src/pages/projects/project-information/utils/pre-examination-sub-stages.js
> +	if (dayToday.isAfter(dayOpenDate) && (dayToday.isBefore(dayClosedDate) || closedDate === null))
The description just wouldn't show. 

`<p class="govuk-body">
	{% if preExamSubStages.PRE_REPS %}
		{{ preRepsDescText | safe }}
	{% elseif preExamSubStages.OPEN_REPS %}
		{{ repsOpenDescText | safe }}
	{% elseif preExamSubStages.CLOSED_REPS %}
		{{ repsClosedDescText | safe }}
	{% elseif preExamSubStages.PUBLISHED_REPS %}
		{{ repsPublishedDescText | safe }}
	{% elseif preExamSubStages.RULE_6_PUBLISHED_REPS %}
		{{ preLimDescText | safe }}
	{% endif %}
</p>
`

2023-08-16 12:55 UTC, jonathangoulding commented on packages/forms-web-app/src/pages/services.js
> +	const { data, resp_code } = await getDocumentByType(case_ref, 'RULE_6_LETTER');
Can lift it to a const in this file for now then move out at a later time when needed.

2023-08-16 14:20 UTC, Yakitrak approved these changes

2023-08-16 14:23 UTC, merged

2023-09-19 13:29 UTC, AnthonyJWalsh commented
:tada: This PR is included in version 2.15.0 :tada:

The release is available on [GitHub release](https://github.com/Planning-Inspectorate/applications-service/releases/tag/%40pins/forms-web-app%402.15.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: